"""Restore legacy tables and add refresh_tokens

Revision ID: e8c9047c56cc
Revises: 
Create Date: 2026-03-16 22:47:08.247486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8c9047c56cc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_summary',
    sa.Column('roll_no', sa.String(length=255), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('present_days', sa.Integer(), nullable=True),
    sa.Column('absent_days', sa.Integer(), nullable=True),
    sa.Column('leave_days', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('roll_no', 'semester')
    )
    op.create_table('contact_info',
    sa.Column('roll_no', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('pincode', sa.String(), nullable=True),
    sa.Column('phone_primary', sa.String(), nullable=True),
    sa.Column('phone_secondary', sa.String(), nullable=True),
    sa.Column('phone_tertiary', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('roll_no')
    )
    op.create_table('counselor_diary',
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('roll_no', sa.String(length=255), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('meeting_date', sa.Date(), nullable=True),
    sa.Column('remark_category', sa.String(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('action_planned', sa.String(), nullable=True),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('counselor_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('meeting_id')
    )
    op.create_table('extra_curricular',
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('roll_no', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('activity_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('activity_id')
    )
    op.create_table('family_details',
    sa.Column('roll_no', sa.String(length=255), nullable=False),
    sa.Column('parent_guardian_name', sa.String(), nullable=True),
    sa.Column('occupation', sa.String(), nullable=True),
    sa.Column('parent_phone', sa.String(), nullable=True),
    sa.Column('emergency_name', sa.String(), nullable=True),
    sa.Column('emergency_address', sa.String(), nullable=True),
    sa.Column('emergency_phone', sa.String(), nullable=True),
    sa.Column('emergency_email', sa.String(), nullable=True),
    sa.Column('father_name', sa.String(), nullable=True),
    sa.Column('mother_name', sa.String(), nullable=True),
    sa.Column('parent_occupation', sa.String(), nullable=True),
    sa.Column('parent_address', sa.String(), nullable=True),
    sa.Column('parent_email', sa.String(), nullable=True),
    sa.Column('emergency_contact_name', sa.String(), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(), nullable=True),
    sa.Column('emergency_contact_relation', sa.String(), nullable=True),
    sa.Column('emergency_contact_address', sa.String(), nullable=True),
    sa.Column('emergency_contact_email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('roll_no')
    )
    op.create_table('internal_marks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roll_no', sa.String(length=255), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('test_number', sa.Integer(), nullable=True),
    sa.Column('percentage', sa.Numeric(), nullable=True),
    sa.Column('subject_code', sa.String(), nullable=True),
    sa.Column('subject_title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('previous_academics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roll_no', sa.String(length=255), nullable=True),
    sa.Column('qualification', sa.String(), nullable=True),
    sa.Column('school_name', sa.String(), nullable=True),
    sa.Column('passing_year', sa.String(), nullable=True),
    sa.Column('percentage', sa.Numeric(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('institution', sa.String(), nullable=True),
    sa.Column('year_passing', sa.String(), nullable=True),
    sa.Column('board_university', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('semester_grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roll_no', sa.String(length=255), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('subject_code', sa.String(), nullable=True),
    sa.Column('subject_title', sa.String(), nullable=True),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('marks', sa.Numeric(), nullable=True),
    sa.Column('internal_marks', sa.Numeric(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('semester_grades')
    op.drop_table('previous_academics')
    op.drop_table('internal_marks')
    op.drop_table('family_details')
    op.drop_table('extra_curricular')
    op.drop_table('counselor_diary')
    op.drop_table('contact_info')
    op.drop_table('attendance_summary')
    # ### end Alembic commands ###
