"""Add ASIE tables

Revision ID: f8fa0c5e2a68
Revises: i0j1k2l3m4n5
Create Date: 2026-05-25 13:27:05.203295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8fa0c5e2a68'
down_revision: Union[str, Sequence[str], None] = 'i0j1k2l3m4n5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_ai_profiles',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('primary_identity', sa.String(length=100), nullable=True),
    sa.Column('secondary_identity', sa.String(length=100), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('weaknesses', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('placement_probability', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('career_fit', sa.JSON(), nullable=True),
    sa.Column('ai_summary', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('generated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_index(op.f('ix_student_ai_profiles_student_id'), 'student_ai_profiles', ['student_id'], unique=False)
    op.create_table('student_capability_scores',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('academic_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('communication_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('leadership_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('technical_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('creativity_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('sports_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('discipline_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('consistency_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('placement_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('growth_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('spi_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('profile_type', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_index(op.f('ix_student_capability_scores_student_id'), 'student_capability_scores', ['student_id'], unique=False)
    op.create_table('student_growth_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('spi_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('growth_delta', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('generated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'semester', name='uq_student_semester_growth')
    )
    op.create_index(op.f('ix_student_growth_history_id'), 'student_growth_history', ['id'], unique=False)
    op.create_index(op.f('ix_student_growth_history_student_id'), 'student_growth_history', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_growth_history_student_id'), table_name='student_growth_history')
    op.drop_index(op.f('ix_student_growth_history_id'), table_name='student_growth_history')
    op.drop_table('student_growth_history')
    op.drop_index(op.f('ix_student_capability_scores_student_id'), table_name='student_capability_scores')
    op.drop_table('student_capability_scores')
    op.drop_index(op.f('ix_student_ai_profiles_student_id'), table_name='student_ai_profiles')
    op.drop_table('student_ai_profiles')
    # ### end Alembic commands ###
